# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  asteroidos-asteroid-calculator = {
    pname = "asteroidos-asteroid-calculator";
    version = "dd2b9b93afc153c617e81e6ad77caca9162392fb";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-calculator.git";
      rev = "dd2b9b93afc153c617e81e6ad77caca9162392fb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZxcQJF69T0RkB3USAKKmcY8dIHSdQlCVFy7YLIprI3Q=";
    };
    date = "2026-02-21";
  };
  asteroidos-asteroid-calendar = {
    pname = "asteroidos-asteroid-calendar";
    version = "f3c6a437bfeff71f457777f6e8f1d6e5674608dc";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-calendar.git";
      rev = "f3c6a437bfeff71f457777f6e8f1d6e5674608dc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Cl137r2dApBuoWP74zX1rLac1g0x+SaTINA/dGzKhZA=";
    };
    date = "2026-02-28";
  };
  asteroidos-asteroid-compass = {
    pname = "asteroidos-asteroid-compass";
    version = "65bd5d49d41b3f55f001da108e39e79e613ad022";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-compass.git";
      rev = "65bd5d49d41b3f55f001da108e39e79e613ad022";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-n0jDH+4UomueHPeVRVFcCdz03iaSCXS9vb7sulq8nHs=";
    };
    date = "2026-02-28";
  };
  asteroidos-asteroid-diamonds = {
    pname = "asteroidos-asteroid-diamonds";
    version = "af2e8d84617df5b1cee277d6250f96d05d7d58a6";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-diamonds.git";
      rev = "af2e8d84617df5b1cee277d6250f96d05d7d58a6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3v5abQn73dDh7qPHlbR+FrwiXibvEKEVau9Q02qJF5M=";
    };
    date = "2026-02-28";
  };
  asteroidos-asteroid-flashlight = {
    pname = "asteroidos-asteroid-flashlight";
    version = "cd106ae07b9afadca712ae34a3ba8edd1a8f5148";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-flashlight.git";
      rev = "cd106ae07b9afadca712ae34a3ba8edd1a8f5148";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Fc5DrefBTQ03CCd3cUNvEjkyR7p5DVKq4upXdWxt66c=";
    };
    date = "2026-02-21";
  };
  asteroidos-asteroid-hrm = {
    pname = "asteroidos-asteroid-hrm";
    version = "f825486c1c9a8038a97e7689ad4c34a7156c5cb9";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-hrm.git";
      rev = "f825486c1c9a8038a97e7689ad4c34a7156c5cb9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v4GYnB68P+y0Bcb5Y7griLInCArP5PEFY6Q3MjDwx7Y=";
    };
    date = "2026-02-21";
  };
  asteroidos-asteroid-launcher = {
    pname = "asteroidos-asteroid-launcher";
    version = "466609c34490e1879f4b05c0946e3038507796fa";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-launcher.git";
      rev = "466609c34490e1879f4b05c0946e3038507796fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-uZpUw8etilc/t0pmkvhIPuP19Dv993ZIqCM78j13NqI=";
    };
    date = "2026-02-28";
  };
  asteroidos-asteroid-music = {
    pname = "asteroidos-asteroid-music";
    version = "a060d5dc3718ee01fdb70782a7272fce2a39e53a";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-music.git";
      rev = "a060d5dc3718ee01fdb70782a7272fce2a39e53a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UvXAFNMJ4XBFsmoLNTYuULtnFKZMCXpReEMUO9TXOgA=";
    };
    date = "2026-02-28";
  };
  asteroidos-asteroid-stopwatch = {
    pname = "asteroidos-asteroid-stopwatch";
    version = "9c63021c9ebd5887a880954014a6d31545dceaaf";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-stopwatch.git";
      rev = "9c63021c9ebd5887a880954014a6d31545dceaaf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1Tx18wWwLji8jP8e7JqWsX1RwcsfhkzVCG/MEtSKOX0=";
    };
    date = "2026-02-21";
  };
  asteroidos-asteroid-timer = {
    pname = "asteroidos-asteroid-timer";
    version = "f04baa1e99fd867fab9c83b84412def455a1266f";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-timer.git";
      rev = "f04baa1e99fd867fab9c83b84412def455a1266f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sgOXFXPxapUUHxiiUildZGkA28Co/zZRPZJy+qb+9Jw=";
    };
    date = "2026-02-21";
  };
  asteroidos-asteroid-weather = {
    pname = "asteroidos-asteroid-weather";
    version = "32f886f1ea0a9e26121d1c728cae5257fa98fa17";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/asteroid-weather.git";
      rev = "32f886f1ea0a9e26121d1c728cae5257fa98fa17";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-T+6sIHR87Xj4DiSlNLzNbljhzUwUHHU4WJQLn/hpVJw=";
    };
    date = "2026-02-28";
  };
  asteroidos-lipstick = {
    pname = "asteroidos-lipstick";
    version = "b9962d7c81473f6fda1479ae3405fd6f112c6195";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/lipstick.git";
      rev = "b9962d7c81473f6fda1479ae3405fd6f112c6195";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KZIFUINC/HG++iWoI75nWri6YCbF+DcxsrslLBJCMGc=";
    };
    date = "2026-02-28";
  };
  asteroidos-meta-asteroid = {
    pname = "asteroidos-meta-asteroid";
    version = "71878ed09e43cef93a86512149199526ce5e4f3f";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/meta-asteroid.git";
      rev = "71878ed09e43cef93a86512149199526ce5e4f3f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0baPfC7YjNsp3Y+C7yjO6H/WxoR4bDv4KyrmT2/ezsU=";
    };
    date = "2026-02-17";
  };
  asteroidos-meta-smartwatch = {
    pname = "asteroidos-meta-smartwatch";
    version = "3f8b55b48d286f36044b06eb2801ab53d7c490a5";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/meta-smartwatch.git";
      rev = "3f8b55b48d286f36044b06eb2801ab53d7c490a5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9blQ1VWzNjYC+pPmUje4jflkCABR4Kmy6iHAQ03g7EA=";
    };
    date = "2026-02-16";
  };
  asteroidos-qml-asteroid = {
    pname = "asteroidos-qml-asteroid";
    version = "40a1d8befb61ac7066e4ee885f49393f2ec0d377";
    src = fetchgit {
      url = "https://github.com/AsteroidOS/qml-asteroid.git";
      rev = "40a1d8befb61ac7066e4ee885f49393f2ec0d377";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OYmp98UE88wnJ/T9Od5q63pdP33bkqufNwgrcwieO0w=";
    };
    date = "2026-02-14";
  };
  droidian-adaptation-lenovo-bronco = {
    pname = "droidian-adaptation-lenovo-bronco";
    version = "cae81c1df119595ce340a25c39ca42a31a162086";
    src = fetchgit {
      url = "https://github.com/droidian-devices/adaptation-droidian-bronco.git";
      rev = "cae81c1df119595ce340a25c39ca42a31a162086";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GD0yJnKXBhwYI4rwlxxq4XhtdR61Jo+FcYm+haC+odQ=";
    };
    date = "2025-12-13";
  };
  droidian-kernel-lenovo-bronco = {
    pname = "droidian-kernel-lenovo-bronco";
    version = "051a9a15805146d91fa833c25a65af018ef5671a";
    src = fetchgit {
      url = "https://github.com/droidian-devices/linux-android-lenovo-bronco.git";
      rev = "051a9a15805146d91fa833c25a65af018ef5671a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-waLjUlm944WZAuODfji8sJBdnIzPTraCNxozORl4hd8=";
    };
    date = "2026-01-24";
  };
  fossil-kernel-msm-fossil-cw = {
    pname = "fossil-kernel-msm-fossil-cw";
    version = "c0b4c201f2d5a641defe19958a9b4c16f40d866b";
    src = fetchgit {
      url = "https://github.com/fossil-engineering/kernel-msm-fossil-cw.git";
      rev = "c0b4c201f2d5a641defe19958a9b4c16f40d866b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-uf5Vln2M64ksT9BC4/R9gLV2yo6zK0vQeolyCUj/u+o=";
    };
    date = "2023-03-16";
  };
  mer-hybris-bluebinder = {
    pname = "mer-hybris-bluebinder";
    version = "9c15cd87cd13e7176e805f959ee8602c491dd95a";
    src = fetchgit {
      url = "https://github.com/mer-hybris/bluebinder.git";
      rev = "9c15cd87cd13e7176e805f959ee8602c491dd95a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UPn9vp21PKL+KEqDjssiScOA8D3QmSAve7Ktmf9tLIk=";
    };
    date = "2022-11-17";
  };
  mer-hybris-qt5-qpa-hwcomposer-plugin = {
    pname = "mer-hybris-qt5-qpa-hwcomposer-plugin";
    version = "41e7bda3bc7a87a1cffd45d44bf6abef90460b38";
    src = fetchgit {
      url = "https://github.com/mer-hybris/qt5-qpa-hwcomposer-plugin.git";
      rev = "41e7bda3bc7a87a1cffd45d44bf6abef90460b38";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hZOy8ws4/9QFyJrXljanR6az59E8efcSLFb63zWqNCQ=";
    };
    date = "2026-01-09";
  };
  postmarketos-pmaports = {
    pname = "postmarketos-pmaports";
    version = "6a6b1f1e1a2ca4bfbc49ec05b1ec991227e2a769";
    src = fetchgit {
      url = "https://gitlab.postmarketos.org/postmarketOS/pmaports.git";
      rev = "6a6b1f1e1a2ca4bfbc49ec05b1ec991227e2a769";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PDsXXfaLQFyGK6zidMArn/pImIJNr6RQkNgaALTTmjA=";
    };
    date = "2026-03-01";
  };
}
